### ISSUE TITLE
settings.os.embedded_libc value not defined

### ISSUE THREAD

**Issue by JamesPei** [conan-io/examples2#167]
I just try to run an example of [offical tutorial](https://docs.conan.io/2/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html) 
when I  execute `conan install . --output-folder build --build=missing`
I got this:
```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux


======== Computing dependency graph ========
Graph root
    conanfile.py: /home/XXX/github/examples2/tutorial/consuming_packages/conanfile_py/conanfile.py
Requirements
    zlib/1.2.11#fca992a7d96a1b92bd956caa8a97d18f - Cache
Build requirements
    cmake/3.22.6#32cced101c6df0fab43e8d00bd2483eb - Cache

======== Computing necessary packages ========
Requirements
    zlib/1.2.11#fca992a7d96a1b92bd956caa8a97d18f:72c852c5f0ae27ca0b1741e5fd7c8b8be91a590a - Invalid
Build requirements
    cmake/3.22.6#32cced101c6df0fab43e8d00bd2483eb:63fead0844576fc02943e16909f08fcdddd6f44b - Invalid
ERROR: There are invalid packages:
cmake/3.22.6: Invalid: 'settings.os.embedded_libc' value not defined
zlib/1.2.11: Invalid: 'settings.os.embedded_libc' value not defined
ERROR: There are invalid packages:
cmake/3.22.6: Invalid: 'settings.os.embedded_libc' value not defined
zlib/1.2.11: Invalid: 'settings.os.embedded_libc' value not defined
```
why? conan version is 2.9.2，and it's same at conan 2.8.0

**Comment by memsharded** [comment]
Hi @JamesPei 

Thanks for your question.

> settings.os.embedded_libc

This is not an standard default Conan setting.
This means that someone added ``embedded_libc`` as an ``os`` subsetting in your ``settings.yml`` or ``settings_user.yml`` in your cache (which can be installed with ``conan config install``)

Then, your default profile is not defining the ``embedded_libc``, because that is a custom setting Conan is not aware of. That should be solved:

- Make sure to clean your cache, remove the not wanted settings.yml, start from scratch or make sure to ``conan config install`` the right configuration from your organization
- Or add ``os.embedded_libc=something`` in your profiles to satisfy the need of defining it (established by your settings)

**Comment by JamesPei** [comment]
thank you @memsharded 
Problem solved. I'm just a little weird because I'm doing all this in a clean environment, so, I don't know why there are these items in the ~/.conan2/settings.yml; But that's okay. Anyway, everything's fine now

**Comment by memsharded** [comment]
Great, closing the issue as solved then, thanks for your feedback!
